export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const VIEW_CANCEL = 'VIEW_CANCEL';
export const SELECT_SERVICE = 'SELECT_SERVICE';